Algoritmo "Operadores Aritmeticos"
// 
//  
// Descrição   : Operadores Artmeticos
// Autor(a)    : Fábio A. Prado
// Data atual  : 12/2/2021
Var
// Seção de Declarações das variáveis 
   resultado, valor1, valor2, valor3:real

   


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   valor1 := 10
   valor2 := 10
   valor3 := 10
   resultado := ((valor1 + valor2 + valor2) / valor3) % 2
   escreval("resultado",resultado)

Fimalgoritmo